twig:
  file_name_pattern: '*.twig'
  paths:
    '%kernel.project_dir%/src/FrontOfficeBundle/Resources/views': FrontOffice
    '%kernel.project_dir%/src/AdherentBundle/Resources/views': Adherent
    '%kernel.project_dir%/src/PartenaireBundle/Resources/views': Partenaire
    '%kernel.project_dir%/src/AdminBundle/Resources/views': Admin
  globals:
    app_locale: '%app_locale%'

when@test:
  twig:
    strict_variables: true
