twig:
  file_name_pattern: '*.twig'
  globals:
    app_locale: '%app_locale%'
    app_artistService: '@App\Service\ArtistService'
    app_socialService: '@App\Service\SocialService'

when@test:
  twig:
    strict_variables: true
