twig:
  file_name_pattern: '*.twig'
  paths:
    '%kernel.project_dir%/src/FrontOfficeBundle/Resources/views': FrontOffice
    '%kernel.project_dir%/src/AdherentBundle/Resources/views': Adherent
    '%kernel.project_dir%/src/PartenaireBundle/Resources/views': Partenaire
    '%kernel.project_dir%/src/AdminBundle/Resources/views': Admin
  globals:
    app_locale: '%app_locale%'
    app_statistics_contact: '@App\AdminBundle\Service\Statistics\ContactService'
    app_statistics_adherent: '@App\AdminBundle\Service\Statistics\AdherentService'
    app_statistics_partenaire: '@App\AdminBundle\Service\Statistics\PartenaireService'
    app_gestion_cotisations: '@App\AdminBundle\Service\Gestion\CotisationService'
    app_informations: '@App\AppBundle\Service\InformationsService'
    app_services: '@App\ServiceBundle\Service\ServicesService'

when@test:
  twig:
    strict_variables: true
