twig:
  file_name_pattern: '*.twig'
  globals:
    app_locale: '%app_locale%'
    app_parameters: '@App\Service\ParametersService'
    app_services: '@App\Service\ServicesService'

when@test:
  twig:
    strict_variables: true
